name: marrat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"
dependencies:
  flutter:
    sdk: flutter
  auto_route: ^0.6.7
  cached_network_image: ^2.2.0+1
  camera: ^0.5.8+5
  change_app_package_name: ^0.1.2
  cloud_firestore: ^0.14.0+2
  cupertino_icons: ^0.1.3
  firebase_core: ^0.5.0
  firebase_storage: ^4.0.0
  flutter_launcher_icons: ^0.8.0
  flutter_typeahead: ^2.0.0
  geocoder: ^0.2.1
  geoflutterfire: ^2.2.1
  get_it: ^5.0.6
  image_picker: ^0.6.7+4
  injectable: ^1.0.4
  location: ^3.2.4
  path_provider: ^1.6.14
  permission_handler: ^5.1.0+2
  rxdart: ^0.24.1
  stacked: ^1.9.5
  stacked_services: ^0.7.2
  google_fonts: ^1.0.0
  youtube_player_flutter: ^7.0.0+7
  url_launcher: ^6.0.2
  webview_flutter: ^2.0.2
flutter_launcher_icons:
  path: ../

flutter_icons:
  image_path_android: "assets/images/app_icon.png"
  image_path_ios: "assets/images/app_icon.png"
  android: true
  ios: true
  adaptive_icon_background: "assets/images/app_icon.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  auto_route_generator: ^0.6.8
  build_runner: ^1.10.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/images/app_icon.png
    - assets/images/upload.png
    - assets/icons/record_icons/beauty.png
    - assets/icons/record_icons/clock.png
    - assets/icons/record_icons/lightning.png
    - assets/icons/record_icons/photo-camera.png
    - assets/icons/record_icons/speed.png
    - assets/icons/bottom_nav_icons/email.png
    - assets/icons/bottom_nav_icons/home.png
    - assets/icons/bottom_nav_icons/user.png

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat-bold.ttf
        - asset: assets/fonts/montserrat-regular.ttf
    - family: TikTokIcons
      fonts:
        - asset: assets/fonts/TikTokIcons.ttf
